import RPi.GPIO as GPIO
import board


MAIN_5V_PIN = 2
MAIN_3V_PIN = 1

MAIN_GND_PIN = 9


#GPIO PINS
AM2301_DATA_PIN = board.D22

DS18B20_DATA_PIN = board.D4

ML_8511_UV_POWER_PIN = 23
SHT31_TEMP_POWER_PIN = 26
GPIO.setmode(GPIO.BCM)
GPIO.setup(ML_8511_UV_POWER_PIN, GPIO.OUT)
GPIO.setup(SHT31_TEMP_POWER_PIN, GPIO.OUT)
